# Configuration for librarian-puppet. For example:
#
# forge "http://forge.puppetlabs.com"
#
# mod "puppetlabs/razor"
# mod "puppetlabs/ntp", "0.0.3"
#
# mod "apt",
#   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
#
# mod "stdlib",
#   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

forge "https://forgeapi.puppetlabs.com"

# install mysql module
mod 'puppetlabs/mysql'

# puppet module install puppetlabs-vcsrepo --version 0.2.0
mod 'puppetlabs/vcsrepo'

# https://forge.puppetlabs.com/camptocamp/openssl
# puppet module install camptocamp-openssl
mod 'camptocamp/openssl'